services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # ro - Только для чтения
      - ./src/:/var/www/laravel
#    зависит от котейнеров, чтобы не пондимать зря композер и артизан
    depends_on:
      - php
      - mysql

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src/:/var/www/laravel

  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.dockerFile
    volumes:
      - ./src/:/var/www/laravel

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src/:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  mysql_data:
